# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db94ec222c9bb10db59cd1cff5b7a51b7899b942c7b3d9fc83cb761587b31a266f55dbb2b97b47ebc0e481427f0856058d4d6047af98950331e325adae9f693

test:
  secret_key_base: a73b48236d3954bcd0ada869519d37ea0fcac1f3dd3bbe932e4b2ee1251c59cba1c1349ef5faa235e211f0af4497f8790b86c94d0b2325725cfc74c660d62ba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
